### ISSUE TITLE
does this still work cross platform

### ISSUE THREAD

**Issue by TomW1605** [learncodebygaming/pydirectinput#3]
hi

does this still work cross platform? i tried using PyAutoGUI and pynput in an attempt to make my program cross platform but i ran into issues on windows with direct input so started using a custom ctypes basd input method (basically the same as yours but with only key down and up because that is all i needed). i would like to still make this project cross platform but have since completely refactor my code to the new method so it is hard to test (i'm not great at regular commits). 

so will your library work on in a non windows environment? i.e. will it pass through to PyAutoGUI if it is run on unix?

also could you not just have it pass through all the functions of PyAutoGUI that do work on windows so users only need to import your library? like a wrapper that overrides the parts that dont work on windows?

**Comment by learncodebygaming** [comment]
Hi Tom. No it's not cross platform-- it's Windows only. This was really just a one weekend project to help people out who ran into this specific Direct Input issue, so it's not as slick as it could be. What you propose seems like it would work.

**Comment by TomW1605** [comment]
when i get a chance i might have a go at converting this into a PyAutoGUI wrapper

**Comment by TomW1605** [comment]
ok so. i started converting this into a pyautogui wrapper and ended up with having it as basically a replacement for the current windows implementation of pyautogui. not sure where to go from here as i kind of made the changes on the wrong side but here it is: https://github.com/TomW1605/pyautogui/blob/master/pyautogui/_pyautogui_win_direct_input.py

feedback welcome

**Comment by liujohnj** [comment]
Hello, Ben and Tom.  This library works like a dream in Windows.  At least for me it has.  Has anyone modified it so that it works in Linux (Ubuntu/Debian)?  When importing it, there's a pesky "_AttributeError: module 'cyptes' has no attirbute 'windll'_" error.  Do you think that would be a challenge?  (You did in one weekend, Ben, what it would have taken me months ... assuming I could even do it!)  Thanks!

**Comment by TomW1605** [comment]
it shouldn't be too hard but when i tried i ended up rewriting the original windows part of the pyautogui library. i will have another crack at it tomorrow and let you know how it goes.

**Comment by liujohnj** [comment]
That's awesome, Tom.  Let me know how it goes!

**Comment by TomW1605** [comment]
ok so i have made progress. i found the easiest way to replace just the windows parts of pyautogui was to import it then change the platform specific python file it points to for functions. i have committed these changes to my fork if you want to test them. i have not had a chance to test it on anything other than windows yet but i think it should work.

**Comment by TomW1605** [comment]
i also decided to use the code i wrote based on the original pyautogui not on the stuff @learncodebygaming wrote. this is because it was already setup to work as a replacement and it has more of the features implemented.

**Comment by liujohnj** [comment]
Tom, I will test them and get back to you.  Thanks!!!
