### ISSUE TITLE
pydirectinput libary can't interact with OSK.exe (default on-screen-keyboard of Windows platform) 

### ISSUE THREAD

**Issue by RidaShamasneh** [learncodebygaming/pydirectinput#58]

**Comment by Rida-Shamasneh** [comment]
I figured out that the reason is because pydirectinput requires the python process to have administrator privileges to be able to interact properly with osk.exe

**Comment by RidaShamasneh** [comment]
I figured out that the reason is because pydirectinput requires the python process to have administrator privileges to be able to interact properly with osk.exe
