### ISSUE TITLE
Doesn't seem to function as expected

### ISSUE THREAD

**Issue by Catman155** [learncodebygaming/pydirectinput#8]
When I want to relatively move. using move or moveRel with parameters `(0, 1)` in CS:GO. The player makes a 180 and looking at the ground. Did I do anything wrong?

**Comment by Catman155** [comment]
Oops. It was the Raw Input setting in CS:GO

**Comment by KevinZzz35** [comment]
> Oops. It was the Raw Input setting in CS:GO

I got the same problem as yours. What do you mean by Raw Input Setting? Need a factor to fix this problem ?

**Comment by Bertus-W** [comment]
> 
> 
> > Oops. It was the Raw Input setting in CS:GO
> 
> I got the same problem as yours. What do you mean by Raw Input Setting? Need a factor to fix this problem ?

There is a setting in the game. raw mouse input or something. I don't remember if it was supposed to be on or off. but that was the problem for me. I think it needs to be off.

**Comment by KevinZzz35** [comment]
> > > Oops. It was the Raw Input setting in CS:GO
> > 
> > 
> > I got the same problem as yours. What do you mean by Raw Input Setting? Need a factor to fix this problem ?
> 
> There is a setting in the game. raw mouse input or something. I don't remember if it was supposed to be on or off. but that was the problem for me. I think it needs to be off.

I tried this on Apex, and got the same problem, looking on the ground. I guess I need try to set it off too.
