### ISSUE TITLE
Mouse direct input (Move) Not working

### ISSUE THREAD

**Issue by Pro100rus32** [learncodebygaming/pydirectinput#9]
Mouse movement works the same as in pyautogui.

**Comment by TomW1605** [comment]
is this an issue? your comment contradicts the title

**Comment by Pro100rus32** [comment]
> is this an issue? your comment contradicts the title

In pyautogui - there is no direct mouse input. Is there something wrong?

**Comment by TomW1605** [comment]
i am still not sure what the issue is. can you please post some example code and the expected and actual resault

**Comment by Pro100rus32** [comment]
> i am still not sure what the issue is. can you please post some example code and the expected and actual resault

PyDirectInput cannot simulate a mouse in a game that uses direct input. For example, in CS: GO put a sleep(5) and some movement of the mouse, during this time go into the game and you will not notice anything.

**Comment by TomW1605** [comment]
ok i will have a look. could you please post the code you are using that is not working so i can test that and make sure i can reproduce the issue.

**Comment by Pro100rus32** [comment]
> ok i will have a look. could you please post the code you are using that is not working so i can test that and make sure i can reproduce the issue.

```
import pyautogui
import pydirectinput
from time import sleep
sleep(5)
pydirectinput.move(1, None)
```

Move the mouse 1 pixel and you will see. If necessary, I can send a video.

**Comment by TomW1605** [comment]
ok i have found the issue. i will make a pull request that fixes it but will need to wait for @learncodebygaming to merge it.

**Comment by learncodebygaming** [comment]
Hey everyone, @TomW1605. The proposed change doesn't reliably move the mouse the exact number of pixels given in the arguments. But did you find that this `moveRel()` change allowed mouse movement to work in CS:GO? The only real difference between the proposed change and the existing code (which calls `moveTo()`) is the removal of the `MOUSEEVENTF_ABSOLUTE` flag. 

If mouse movement does indeed work with that flag removed: then we can either figure out how to eliminate the pixel distance inconsistencies, or we can create a new method if you specifically want to use this type of mouse movement.

**Comment by TomW1605** [comment]
ok that a fair issue that i admit i did not test thoroughly. i did find that this was the only way to  get mouse movement to work in both CS:GO and Elite Dangerous so we might need to look into it

**Comment by Pro100rus32** [comment]
> Hey everyone, @TomW1605. The proposed change doesn't reliably move the mouse the exact number of pixels given in the arguments. But did you find that this `moveRel()` change allowed mouse movement to work in CS:GO? The only real difference between the proposed change and the existing code (which calls `moveTo()`) is the removal of the `MOUSEEVENTF_ABSOLUTE` flag.
> 
> If mouse movement does indeed work with that flag removed: then we can either figure out how to eliminate the pixel distance inconsistencies, or we can create a new method if you specifically want to use this type of mouse movement.

Its working!!!))



> ok that a fair issue that i admit i did not test thoroughly. i did find that this was the only way to get mouse movement to work in both CS:GO and Elite Dangerous so we might need to look into it

thanks!)

**Comment by Pro100rus32** [comment]
> Hey everyone, @TomW1605. The proposed change doesn't reliably move the mouse the exact number of pixels given in the arguments. But did you find that this `moveRel()` change allowed mouse movement to work in CS:GO? The only real difference between the proposed change and the existing code (which calls `moveTo()`) is the removal of the `MOUSEEVENTF_ABSOLUTE` flag.
> 

If `moveTo()` will work the same as `moveRel()` now. That will be great!

**Comment by TomW1605** [comment]
while posable this is somewhat what impractical if the relative move is not accurate.

@learncodebygaming would it work to add a flag or some other method that swaps between the 2 methods (both absolute/both relative)?

**Comment by learncodebygaming** [comment]
Yeah @TomW1605 I think that's exactly what we should do. I'll add a parameter to each of those methods that will switch them into relative mode.

I was able to test this today with Elite Dangerous, and what makes games like it and CS:GO different is that wherever your mouse is when you focus the game window: the game treats that mouse position as the center position on the screen. Then any mouse movements from that initial position will turn your character left/right/up/down, relative to that initial position. So in this situation the relative mouse movement calls make more sense than absolute.

I'll get this implemented and rollout an update shortly.

**Comment by learncodebygaming** [comment]
I've pushed this change out as version 1.0.3. Use the optional "relative" parameter to use the relative mouse movement method (without the `MOUSEEVENTF_ABSOLUTE` flag). Examples:

```
pydirectinput.moveRel(0, -400, relative=True)
pydirectinput.move(200, 400, relative=True)
pydirectinput.moveTo(1150, 0, relative=True)
```
Thanks for everyone's help!
